// Generated by CoffeeScript 1.10.0
(function() {
  var https;

  https = require('https');

  module.exports = {
    printName: function(person) {
      return person.last + ", " + person.first;
    },
    loadWiki: function(person, callback) {
      var url;
      url = "https://en.wikipedia.org/" + person.first + "_" + person.last;
      return https.get(url, function(res) {
        var body;
        body = "";
        res.setEncoding('utf8');
        res.on('data', function(chunk) {
          return body += chunk;
        });
        return res.on('end', function() {
          return callback(body);
        });
      });
    }
  };

}).call(this);
