// Generated by CoffeeScript 1.10.0
(function() {
  var printMessage, setTitle, ws;

  ws = new WebSocket('ws://localhost:3333');

  ws.onopen = function() {
    return setTitle('Connected');
  };

  ws.onclose = function() {
    return setTitle('disconnected');
  };

  ws.onmessage = function(payload) {
    return printMessage(payload.data);
  };

  document.forms[0].onsubmit = function() {
    var input;
    input = document.getElementById('message');
    ws.send(input.value);
    return input.value = '';
  };

  setTitle = function(title) {
    return document.querySelector('hi').innerHTML = title;
  };

  printMessage = function(message) {
    var p;
    p = document.createElement('p');
    p.innerText = message;
    return document.querySelector('div.messages').appendChild(p);
  };

}).call(this);

//# sourceMappingURL=ws-client.js.map
