// Generated by CoffeeScript 1.10.0
(function() {
  var Server, wss;

  Server = require('ws').Server;

  wss = new Server({
    port: 3333
  });

  wss.on('connection', function(ws) {
    ws.on('message', function(message) {
      var each, i, len, ref, results;
      if (message === 'exit') {
        return ws.close();
      } else {
        ref = wss.clients;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          each = ref[i];
          results.push(each.send(message));
        }
        return results;
      }
    });
    return ws.send('Welcome');
  });

}).call(this);

//# sourceMappingURL=ws.js.map
