// Generated by CoffeeScript 1.10.0
(function() {
  var wss;

  wss = new require('ws').Server({
    port: 3333
  });

  wss.on('connection', function(ws) {
    return ws.send('Welcome');
  });

}).call(this);

//# sourceMappingURL=ws.js.map
