// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, http, io, server;

  express = require('express');

  http = require('http');

  app = express();

  server = http.createServer(app).listen(3000);

  io = (require('socket.io'))(server);

  app.use(express["static"]('./public'));

  io.on('connection', function(socket) {
    socket.on('chat', function(message) {
      return socket.broadcast.emit('message', message);
    });
    return socket.emit('message', 'welcome...');
  });

  console.log('starting.....');

}).call(this);

//# sourceMappingURL=sockio-server.js.map
